In [23]:
import numpy as np
from scipy.linalg import expm, logm, sqrtm

In [24]:
F = np.array([
    [2, 1, 0], 
    [0, 1, -1], 
    [0, 0, 0.5]
]) # deformation gradient

In [25]:
L = logm(F) # velocity gradient

In [26]:
D = (L + L.T) / 2 # 

In [27]:
W = (L - L.T) / 2 # spin tensor

In [28]:
Fd = expm(D) # pure body distorsion
Fr = expm(W) # 

In [29]:
Fd @ Fr # before rotation

array([[ 1.78860024,  1.22354987,  0.00424776],
       [ 0.28547732,  0.78057789, -1.17427483],
       [ 0.03668305,  0.07643806,  0.85226578]])

In [30]:
Fr @ Fd # or after rotation

array([[ 2.12897109,  0.85673624, -0.00559183],
       [-0.26389106,  1.13722643, -0.84226639],
       [-0.30663783,  0.2060087 ,  0.15524638]])

# Rotace (rigid body deformation) a distorsion mohou působit současně nebo v superpozici

In [31]:
expm(logm(Fd) + logm(Fr))

array([[ 2.00000000e+00,  1.00000000e+00,  6.11973738e-16],
       [-1.60171325e-16,  1.00000000e+00, -1.00000000e+00],
       [ 8.40899457e-16,  3.60385482e-16,  5.00000000e-01]])

# Voigt notation