# Linear algebra

$$ 
\renewcommand{\vec}[1]{\mathbf{#1}} 
$$

This document shows how to translate the language of algebra to Python with help of NumPy library.

In [51]:
import numpy as np

# Modify the settings of interactove shell to show all expression outputs (not only the last one).
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Axiomatická definice vektorového prostoru

Jako lineární nebo vektorvý prostor označujem množinu prvků (vektorů) s operacemi `+`, `.` které splňují podmínky:

1. $ \vec{u} + \vec{v} = \vec{v} + \vec{u} $ (komutativita sčítaní vektorů)
2. $\alpha (\vec{u} + \vec{v}) = \alpha \vec{u} + \alpha \vec{v}$ (asociativita)
3. existuje nulový prvek $\vec{0}$.
4. existuje opačný prvek $-\vec{u}$.


## Vektorový prostor $E^3$

Bázi vektorového prostoru v $E^3$ tvoří tři ortonormální vektory označované jako $i$, $j$, $k$ nebo $e_i$, kde $i \in {1, 2, 3}$.  

Definice bázových vektorů $E^3$ pomocí *NumPy*. 

In [52]:
e1 = np.array([1, 0, 0], dtype=np.float) # Explicitní zadání typu provede konverzi z int na float.
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])

Nyní jsou e1, e2 a e3 instancemi třídy `ndarray` s čásleným typen float.

Definice pomocí standardního Pythonu.

In [37]:
type(e1)

numpy.ndarray

In [38]:
e1.dtype

dtype('float64')

Pro další práce si nadefinujem dva vektory $\vec{u}$ a $\vec{v}$. 

In [39]:
u = e1
v = e2

# Operations

## Vector addition

$\vec{u} + \vec{v} = \vec{v} + \vec{u} $

In [46]:
(u + v)
((u + v) == (v + u)).all()

array([1., 1., 0.])

True

## Vector subtraction

$ \vec{u} - \vec{v} = \vec{v} - \vec{u} $

## Multiplication of vector by scalar

$ \lambda \vec{u} = \vec{u}\lambda$

In [47]:
2.0 * u
u * 2.0

array([2., 0., 0.])

array([2., 0., 0.])

## Vector space with scalar product

The scalar product or *inner product* can be computed with the `numpy.dot()` which is a free function in the `numpy` namespace or `ndarray.dot()` whoc is the method of `ndarray` class instance.

Documentation [`dot`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)

`a` a `b` pole dimenze jedna (1D), pak `dot(a, b)` vrací *inner procuct* tj. skalární součin dvou vektorů.

In [53]:
np.dot(e1, e2)

0.0

Pokud jem `a` instancí `ndarray` můžeme použít jeho metody `dot`.

In [8]:
e1.dot(e2)

0.0

## Klíčové koncepty

- báze, bázový vektor
- jednotkový vektor
- nulový vektor
- ortogonalita 
- ortonormalita
- skalární součin
- vektorový součin 
- smíšený součin

$$ 
\begin{equation} 
e = mc^2 
\end{equation} 
$$ 